name: diracx
channels:
  - diracgrid
  - conda-forge
  - nodefaults
dependencies:
  - authlib
  - aiobotocore
  - botocore
  - cachetools
  # Needed because coverage runs inside the image
  # when doing the integration tests
  - coverage
  - email-validator
  - git
  - gitpython
  - httpx
  - joserfc
  - pip
  - pydantic >=2
  - pydantic-settings
  - python =3.11
  - pyyaml
  - pyjwt
  - requests
  - urllib3 <2
  - sh
  - tini
  - zstandard